"use client";

import { CircleAlert, ExternalLink, FileText, Hash, ImageOff, LoaderCircle, RefreshCw, ScanFace, ShieldCheck, Upload } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import SiteNav from "@/components/site-nav";
import { evidenceMediaUrl, listEvidence, readEvidenceRecord, type EvidenceSummary } from "@/lib/api";
import { platformFor } from "@/lib/platform";

function percent(value?: number | null) {
  return typeof value === "number" ? `${(value * 100).toFixed(1)}%` : "—";
}

function show(value: unknown) {
  return value === undefined || value === null || value === "" ? "—" : String(value);
}

function timeAgo(iso?: string | null) {
  if (!iso) return "—";
  const then = Date.parse(iso);
  if (Number.isNaN(then)) return "—";
  const mins = Math.max(0, Math.round((Date.now() - then) / 60000));
  if (mins < 1) return "just now";
  if (mins < 60) return `${mins} min ago`;
  const hours = Math.round(mins / 60);
  if (hours < 24) return `${hours} hr ago`;
  return `${Math.round(hours / 24)} d ago`;
}

/** A stored evidence image, or an explicit placeholder when none was kept. */
function EvidenceImage({ src, alt, caption }: { src?: string; alt: string; caption: string }) {
  return (
    <figure className="evidence-figure">
      {src ? (
        <img src={src} alt={alt} />
      ) : (
        <div className="figure-missing">
          <ImageOff size={20} />
          <span>Not stored</span>
        </div>
      )}
      <figcaption>{caption}</figcaption>
    </figure>
  );
}

export default function EvidencePage() {
  const [records, setRecords] = useState<EvidenceSummary[] | null>(null);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [detail, setDetail] = useState<Record<string, unknown> | null>(null);
  const [query, setQuery] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [localFile, setLocalFile] = useState<string | null>(null);

  const load = useCallback(() => {
    setLoading(true);
    listEvidence()
      .then((data) => {
        setRecords(data.records);
        setError(null);
        setSelectedId((current) => current ?? data.records[0]?.evidence_id ?? null);
      })
      .catch((caught: Error) => setError(caught.message))
      .finally(() => setLoading(false));
  }, []);

  useEffect(load, [load]);

  useEffect(() => {
    if (!selectedId) { setDetail(null); return; }
    setLocalFile(null);
    readEvidenceRecord(selectedId)
      .then((data) => setDetail(data))
      .catch((caught: Error) => setError(caught.message));
  }, [selectedId]);

  const filtered = useMemo(() => {
    if (!records) return [];
    const needle = query.trim().toLowerCase();
    if (!needle) return records;
    return records.filter((record) =>
      `${record.evidence_id} ${record.platform ?? ""} ${record.post_url ?? ""}`.toLowerCase().includes(needle)
    );
  }, [records, query]);

  const withImages = useMemo(
    () => (records ?? []).filter((record) => record.has_matched_image || record.has_query_image).length,
    [records]
  );
  const sourceCount = useMemo(
    () => new Set((records ?? []).map((record) => record.platform).filter(Boolean)).size,
    [records]
  );

  const openLocalFile = async (file: File | undefined) => {
    if (!file) return;
    try {
      const parsed = JSON.parse(await file.text());
      setDetail(parsed);
      setSelectedId(null);
      setLocalFile(file.name);
      setError(null);
    } catch {
      setError("That file is not valid evidence JSON.");
    }
  };

  const postUrl = typeof detail?.post_url === "string" ? detail.post_url : undefined;
  const { Icon: DetailIcon, label: detailPlatform } = platformFor(postUrl ?? String(detail?.platform ?? ""));
  const detailId = typeof detail?.evidence_id === "string" ? detail.evidence_id : null;
  const detailMedia = (detail?.media ?? {}) as Record<string, string | undefined>;
  // Local files are read from disk and have no server-side media to fetch.
  const canLoadMedia = Boolean(detailId && !localFile);

  return (
    <main>
      <SiteNav />
      <section className="records-head">
        <div>
          <p className="kicker">Discovered · verified · sealed</p>
          <h1>Evidence records</h1>
          <p className="lede">
            Every record generated by a pipeline run on this machine: the face that was scanned, the image
            it matched on the web, the scores behind the decision, and the on-chain proof.
          </p>
        </div>
        <div className="records-actions">
          <label className="file-picker compact">
            <Upload size={14} /> Open a JSON file
            <input type="file" accept="application/json,.json" onChange={(event) => void openLocalFile(event.target.files?.[0])} />
          </label>
          <button className="theme-btn wide" onClick={load} aria-label="Refresh records">
            <RefreshCw size={14} /> Refresh
          </button>
        </div>
      </section>

      <section className="stat-strip">
        <div className="stat"><div className="num">{records?.length ?? "—"}</div><div className="label">Stored records</div></div>
        <div className="stat"><div className="num">{records ? withImages : "—"}</div><div className="label">With stored imagery</div></div>
        <div className="stat"><div className="num">{records ? sourceCount : "—"}</div><div className="label">Distinct sources</div></div>
        <div className="stat"><div className="num small">{records?.[0] ? timeAgo(records[0].verification_timestamp) : "—"}</div><div className="label">Most recent record</div></div>
      </section>

      {error && <div className="page-error"><CircleAlert size={15} /> {error}</div>}

      <section className="records-split">
        <aside className="records-list">
          <input
            className="records-search"
            placeholder="Search by id, platform, or URL"
            value={query}
            onChange={(event) => setQuery(event.target.value)}
          />
          {loading && <div className="empty-note"><LoaderCircle className="spin" size={14} /> Loading records…</div>}
          {!loading && filtered.length === 0 && (
            <div className="empty-note">
              {records && records.length === 0
                ? "No evidence records yet. Run a scan on the home page to generate one."
                : "No records match that search."}
            </div>
          )}
          {filtered.map((record) => {
            const { Icon, label } = platformFor(record.post_url ?? record.platform ?? "");
            return (
              <button
                key={record.evidence_id}
                className={`record-card ${selectedId === record.evidence_id ? "active" : ""}`}
                onClick={() => setSelectedId(record.evidence_id)}
              >
                <span className="record-thumb">
                  {record.has_matched_image ? (
                    <img src={evidenceMediaUrl(record.evidence_id, "match")} alt="" />
                  ) : (
                    <ImageOff size={16} />
                  )}
                </span>
                <span className="record-body">
                  <span className="record-top">
                    <Icon size={13} />
                    <span className="record-platform">{label}</span>
                  </span>
                  <span className="record-id">{record.evidence_id.slice(0, 8)}…{record.evidence_id.slice(-4)}</span>
                  <span className="record-meter">
                    <span className="meter"><i style={{ width: `${Math.min(100, (record.final_confidence ?? 0) * 100)}%` }} /></span>
                    <b>{percent(record.final_confidence)}</b>
                  </span>
                </span>
              </button>
            );
          })}
        </aside>

        <div className="record-detail">
          {!detail ? (
            <div className="output-empty">
              <FileText className="icon" size={28} />
              <strong>Select a record</strong>
              <p>Choose an evidence record on the left, or open a JSON file from disk.</p>
            </div>
          ) : (
            <>
              <div className="detail-head">
                <div>
                  <p className="kicker">{localFile ? `Local file · ${localFile}` : "Stored evidence record"}</p>
                  <h2>{show(detail.evidence_id)}</h2>
                </div>
                <span className={`badge ${detail.final_confidence ? "success" : "neutral"}`}>
                  {detail.final_confidence ? "Match sealed" : "No match"}
                </span>
              </div>

              <div className="comparison">
                <EvidenceImage
                  src={canLoadMedia && detailMedia.query_image ? evidenceMediaUrl(detailId!, "query") : undefined}
                  alt="The face that was scanned"
                  caption="Scanned face"
                />
                <div className="comparison-middle">
                  <span className="comparison-score">{percent(detail.face_similarity as number)}</span>
                  <span className="comparison-label">face similarity</span>
                  <span className="comparison-rule" />
                  <span className="comparison-final">{percent(detail.final_confidence as number)}</span>
                  <span className="comparison-label">final confidence</span>
                </div>
                <EvidenceImage
                  src={canLoadMedia && detailMedia.matched_image ? evidenceMediaUrl(detailId!, "match") : undefined}
                  alt="The image found on the web"
                  caption="Matched on the web"
                />
              </div>

              <div className="detail-group">
                <div className="detail-group-title">Discovered source</div>
                <div className="source-line">
                  <span className="platform-icon"><DetailIcon size={16} /></span>
                  <div>
                    <strong>{detailPlatform}</strong>
                    <span>{show(detail.post_url ?? detail.post_id)}</span>
                  </div>
                  {postUrl && (
                    <a className="jump-link" href={postUrl} target="_blank" rel="noreferrer">
                      Open source <ExternalLink size={12} />
                    </a>
                  )}
                </div>
                <div className="data-row"><span>Search provider</span><span className="val">{show((detail.search as Record<string, unknown> | undefined)?.provider)}</span></div>
                <div className="data-row"><span>Sealed at</span><span className="val">{show(detail.verification_timestamp)}</span></div>
              </div>

              <div className="detail-columns">
                <div className="detail-group">
                  <div className="detail-group-title"><ScanFace size={13} /> Face verification</div>
                  <div className="data-row"><span>Face similarity</span><span className="val">{percent(detail.face_similarity as number)}</span></div>
                  <div className="data-row"><span>Image similarity</span><span className="val">{percent(detail.image_similarity as number)}</span></div>
                  <div className="data-row"><span>Metadata consistency</span><span className="val">{percent(detail.metadata_consistency as number)}</span></div>
                  <div className="data-row"><span>Threshold</span><span className="val">{percent(detail.match_threshold as number)}</span></div>
                  <div className="data-row"><span>Final confidence</span><span className="val strong">{percent(detail.final_confidence as number)}</span></div>
                </div>

                <div className="detail-group">
                  <div className="detail-group-title"><Hash size={13} /> Cryptographic evidence</div>
                  <div className="data-row"><span>Evidence id</span><span className="val">{show(detail.evidence_id)}</span></div>
                  <div className="data-row"><span>Pipeline id</span><span className="val">{show(detail.pipeline_id)}</span></div>
                  <div className="data-row"><span>Search id</span><span className="val">{show((detail.search as Record<string, unknown> | undefined)?.search_id)}</span></div>
                  <div className="data-row"><span>Matched image hash</span><span className="val">{show(detail.image_hash)}</span></div>
                  <div className="data-row"><span>Record version</span><span className="val">{show(detail.version)}</span></div>
                </div>
              </div>

              <details className="raw-json">
                <summary><Hash size={13} /> Raw canonical record</summary>
                <pre className="json-viewer">{JSON.stringify(detail, null, 2)}</pre>
              </details>

              <p className="detail-foot">
                <ShieldCheck size={13} /> To confirm this record still matches the chain, open the Verify page and submit its JSON.
              </p>
            </>
          )}
        </div>
      </section>
    </main>
  );
}
