"""Read access to evidence records generated by previous pipeline runs."""

import json
from pathlib import Path
from typing import Any

from fastapi import APIRouter
from fastapi.responses import FileResponse

from src.api.errors import ApiFailure
from src.config import settings
from src.verification.evidence import media_dir

router = APIRouter(tags=["evidence"])


def _evidence_dir() -> Path:
    return Path(settings.EVIDENCE_DIR)


def _load(path: Path) -> dict[str, Any]:
    try:
        record = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ApiFailure("EVIDENCE_UNREADABLE", f"Evidence file could not be read: {path.name}", 422) from exc
    if not isinstance(record, dict):
        raise ApiFailure("EVIDENCE_UNREADABLE", f"Evidence file is not a JSON object: {path.name}", 422)
    return record


@router.get("/evidence", summary="List stored evidence records")
def list_evidence() -> dict[str, Any]:
    directory = _evidence_dir()
    if not directory.is_dir():
        return {"count": 0, "records": []}
    files = sorted(directory.glob("*.json"), key=lambda item: item.stat().st_mtime, reverse=True)
    records = []
    for path in files:
        try:
            record = _load(path)
        except ApiFailure:
            continue
        media = record.get("media") if isinstance(record.get("media"), dict) else {}
        records.append({
            "evidence_id": record.get("evidence_id", path.stem),
            "platform": record.get("platform"),
            "post_url": record.get("post_url"),
            "final_confidence": record.get("final_confidence"),
            "face_similarity": record.get("face_similarity"),
            "image_similarity": record.get("image_similarity"),
            "query_image_hash": record.get("query_image_hash"),
            "verification_timestamp": record.get("verification_timestamp"),
            "has_query_image": bool(media.get("query_image")),
            "has_matched_image": bool(media.get("matched_image")),
            "created_at": path.stat().st_mtime,
        })
    return {"count": len(records), "records": records}


@router.get("/evidence/{evidence_id}/media/{kind}", summary="Read an image stored with an evidence record")
def read_evidence_media(evidence_id: str, kind: str) -> FileResponse:
    if kind not in {"query", "match"}:
        raise ApiFailure("INVALID_MEDIA_KIND", "Media kind must be 'query' or 'match'.", 400)
    record = read_evidence(evidence_id)
    media = record.get("media")
    if not isinstance(media, dict):
        raise ApiFailure("MEDIA_NOT_FOUND", "This record has no stored images.", 404)
    name = media.get("query_image" if kind == "query" else "matched_image")
    if not isinstance(name, str) or "/" in name or "\\" in name:
        raise ApiFailure("MEDIA_NOT_FOUND", f"No {kind} image stored for this record.", 404)
    path = media_dir() / name
    if not path.is_file():
        raise ApiFailure("MEDIA_NOT_FOUND", f"The {kind} image file is missing.", 404)
    return FileResponse(path)


@router.get("/evidence/{evidence_id}", summary="Read one stored evidence record")
def read_evidence(evidence_id: str) -> dict[str, Any]:
    if "/" in evidence_id or "\\" in evidence_id or evidence_id.startswith("."):
        raise ApiFailure("INVALID_EVIDENCE_ID", "Evidence id is not valid.", 400)
    path = _evidence_dir() / f"{evidence_id}.json"
    if not path.is_file():
        raise ApiFailure("EVIDENCE_NOT_FOUND", f"No stored evidence record with id {evidence_id}.", 404)
    return _load(path)
